steps:

#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'gcr.io/$PROJECT_ID/telbot', '.']
#    images: ['gcr.io/$PROJECT_ID/telbot']
#
  - name: "gcr.io/cloud-builders/mvn"
    args: ["clean", "integration-test", "-DtestSuite=testngUnitTests"]
    waitFor: ['-']

#  - name: "gcr.io/cloud-builders/mvn"
#    args: ["clean", "integration-test", "-DtestSuite=testng"]
#    waitFor: ['-']

#  - name: 'bash'
#    args: ['pwd']

  - name: 'bash'
    args: ["ls", "-R"]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '-d', '-p', '4545:80', 'nginx']
    wait_for: ['latest']

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "app.standard.yaml"]

timeout: "1600s"

