steps:

#  - name: "gcr.io/cloud-builders/mvn"
#    args: ["clean", "integration-test"]
#    waitFor: ['-']

#  - name: "gcr.io/cloud-builders/mvn"
#    args: ["clean", "integration-test", "-DtestSuite=testng"]

#  - name: 'bash'
#    args: ['mkdir java && cd java']

  - name: 'gcr.io/cloud-builders/wget'
    args: ['https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz']

  - name: 'gcr.io/cloud-builders/wget'
    args: ['https://github.com/allure-framework/allure2/releases/download/2.13.9/allure-2.13.9.zip']


  - name: 'ubuntu'
    args: ['bash', '-c','tar zxvf openjdk-11.0.1_linux-x64_bin.tar.gz && cd jdk-11.0.1/bin && apt-get update && apt-get install -y unzip && unzip ../../allure-2.13.9.zip && allure-2.13.9/bin/allure --version && pwd']

    #export JAVA_HOME=/workspace/jdk-11.0.1 && export PATH=/workspace/jdk-11.0.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

#&& apt install wget
  - name: 'bash'
    args: ['printenv']

#
#  - name: 'ubuntu'
#    args: ['bash', '-c','pwd apt-get update && apt-get install -y unzip && unzip allure-2.13.9.zip && allure-2.13.9/bin/allure --version && pwd']

#  - name: 'gcr.io/cloud-builders/java'
#


#  - name: "gcr.io/cloud-builders/gcloud"
#    args: ["app", "deploy", "app.standard.yaml"]



timeout: "1600s"

