steps:

#  - name: "gcr.io/cloud-builders/mvn"
#    args: ["clean", "integration-test"]
#    waitFor: ['-']

#  - name: "gcr.io/cloud-builders/mvn"
#    args: ["clean", "integration-test", "-DtestSuite=testng"]
#    waitFor: ['-']

  #  - name: 'bash'
  #    args: ['pwd']
  - name: 'gcr.io/cloud-builders/wget'
    args: ['https://github.com/allure-framework/allure2/releases/download/2.13.9/allure-2.13.9.zip']

  - name: 'ubuntu'
    args: ['bash', '-c','apt-get install -y unzip && unzip allure-2.13.9.zip && allure-2.13.9/bin/allure --version']

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "app.standard.yaml"]



timeout: "1600s"

