steps:
  - name: "gcr.io/cloud-builders/mvn"
    args: ["clean", "integration-test", "-DtestSuite=testngUnitTests"]
    waitFor: ['-']
#
#  - name: "gcr.io/cloud-builders/mvn"
#    args: ["clean", "integration-test", "-DtestSuite=testng"]
#    waitFor: ['-']

#  - name: 'gcr.io/cloud-builders/gcloud'
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - allure serve allure-results

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "app.standard.yaml"]

timeout: "1600s"

#- name: 'gcr.io/cloud-builders/docker'
# args: ['build', '-t', 'gcr.io/$PROJECT_ID/telbot', '.']
#images: ['gcr.io/$PROJECT_ID/telbot']