steps:

#  - name: 'gcr.io/cloud-builders/wget'
#    args: ['https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz']
#
#  - name: 'gcr.io/cloud-builders/wget'
#    args: ['https://github.com/allure-framework/allure2/releases/download/2.13.9/allure-2.13.9.zip']

#  - name: "gcr.io/cloud-builders/mvn"
#    args: ["clean", "integration-test", "-DtestSuite=testngone"]

#  - name: 'ubuntu'
#    args: ['bash', '-c','chmod +x allure.sh && ./allure.sh']

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "app.standard.yaml"]

timeout: "1600s"

